nelmio_api_doc:
    documentation:
        servers:
            - url: http://127.0.0.1:8000/
              description: API
        info:
            title: Bilemo
            description: Api Bilemo
            version: 1.0.0
        security:
            - Bearer: []
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    in: header
                    name: Authorization
                    scheme: bearer
                    bearerFormat: JWT

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
